version: '3'
services:
  main_service:
    build:
      context: ./main_service
    ports:
      - "8080:8080"

  condition_checker:
    build:
      context: ./condition_checker
    ports:
      - "5001:5001"

  service_1:
    build:
      context: ./service_1
    ports:
      - "5002:5002"

  service_2:
    build:
      context: ./service_2
    ports:
      - "5003:5003"

  service_3:
    build:
      context: ./service_3
    ports:
      - "5004:5004"
